DROP TABLE RESERVATION;

CREATE TABLE RESERVATION (
	RSV_CD	NUMBER		NOT NULL,
	FAC_CD	NUMBER		NOT NULL,
	MEM_CD	NUMBER		NOT NULL,
	RSV_ST	DATE		NULL,
	RSV_EN	DATE		NULL
);

DROP TABLE NOTICE;

CREATE TABLE NOTICE (
	NTC_CD	NUMBER		NOT NULL,
	MGR_CD	NUMBER		NOT NULL,
	NTC_TTL	VARCHAR2(100)		NULL,
	NTC_CON	VARCHAR2(1000)		NULL,
	NTC_CATE	VARCHAR2(10)		NULL,
	NTC_DT	DATE		NULL,
	NTC_HIT	NUMBER		NULL,
	NTC_HOT	NUMBER		NULL
);

DROP TABLE A_SCHEDULE;

CREATE TABLE A_SCHEDULE (
	ASCH_CD	NUMBER		NOT NULL,
	ASCH_MEM	VARCHAR2(10)		NULL,
	ASCH_CATE	VARCHAR2(10)		NULL,
	ASCH_CON	VARCHAR2(100)		NULL,
	ASCH_ST	DATE		NULL,
	ASCH_EN	DATE		NULL
);

DROP TABLE PAYMENT;

CREATE TABLE PAYMENT (
	PAY_CD	NUMBER		NOT NULL,
	STU_ID	NUMBER		NOT NULL,
	PAY_SEM	NUMBER		NULL,
	PAY_DT	DATE		NULL,
	PAY_AMT	NUMBER		NULL,
	PAY_YN	NUMBER		NULL
);

DROP TABLE P_SCHOLARSHIP;

CREATE TABLE P_SCHOLARSHIP (
	PSCL_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	SCL_CD	NUMBER		NOT NULL,
	PSCL_SEM	NUMBER		NULL,
	PSCL_DT	DATE		NULL,
	PSCL_CON	VARCHAR2(300)		NULL,
	PSCL_YN	NUMBER		NULL
);

DROP TABLE SCHOLARSHIP;

CREATE TABLE SCHOLARSHIP (
	SCL_CD	NUMBER		NOT NULL,
	SCL_NM	VARCHAR2(30)		NULL,
	SCL_AMT	NUMBER		NULL,
	SCL_DETAIL	VARCHAR2(500)		NULL,
	SCL_MAX	NUMBER		NULL
);

DROP TABLE ROOM;

CREATE TABLE ROOM (
	ROOM_CD	NUMBER		NULL,
	BLD_CD	NUMBER		NULL,
	ROOM_NO	NUMBER		NOT NULL,
	ROOM_MAX	NUMBER		NOT NULL
);

DROP TABLE CRITERIA;

CREATE TABLE CRITERIA (
	CRTR_CD	NUMBER		NOT NULL,
	LECA_CD	NUMBER		NOT NULL,
	CRTR_MP	NUMBER		NULL,
	CRTR_FP	NUMBER		NULL,
	CRTR_TP	NUMBER		NULL,
	CRTR_AP	NUMBER		NULL
);

DROP TABLE OBJECTION;

CREATE TABLE OBJECTION (
	OBJ_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	OBJ_TTL	VARCHAR2(150)		NULL,
	OBJ_CON	VARCHAR2(1000)		NULL,
	OBJ_DT	DATE		NULL,
	OBJ_YN	NUMBER		NULL,
	OBJ_RPL	VARCHAR2(1000)		NULL
);

DROP TABLE TASK;

CREATE TABLE TASK (
	TASK_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	TASK_NM	VARCHAR2(100)		NULL,
	TASK_CON	VARCHAR2(500)		NULL,
	TASK_DT	DATE		NULL,
	TASK_FNM	VARCHAR2(100)		NULL
);

DROP TABLE STU_TEST;

CREATE TABLE STU_TEST (
	ST_CD	NUMBER		NOT NULL,
	TEST_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	ST_SCORE	NUMBER		NULL
);

DROP TABLE ATTENADENCE;

CREATE TABLE ATTENADENCE (
	ATEN_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	ATEN_CATE	DATE		NULL,
	ATEN_DT	VARCHAR2(10)		NULL
);

DROP TABLE COUNSEL;

CREATE TABLE COUNSEL (
	CNSL_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	CNSL_TTL	VARCHAR2(100)		NULL,
	CNSL_CON	VARCHAR2(1000)		NULL,
	CNSL_REG	DATE		NULL,
	CNSL_DT	DATE		NULL,
	CNSL_RPL	VARCHAR2(1000)		NULL,
	CNSL_YN	NUMBER		NULL,
	CNSL_CATE	VARCHAR2(10)		NULL
);

DROP TABLE EVALUATION_Q;

CREATE TABLE EVALUATION_Q (
	EVLQ_CD	NUMBER		NOT NULL,
	EVLQ_CON	VARCHAR2(300)		NULL
);

DROP TABLE STUDENT;

CREATE TABLE STUDENT (
	STU_CD	NUMBER		NOT NULL,
	DEP_CD	NUMBER		NOT NULL,
	STU_YR	NUMBER		NULL,
	STU_SEM	NUMBER		NULL,
	STU_MRC	NUMBER		NULL,
	STU_MOC	NUMBER		NULL,
	STU_CRC	NUMBER		NULL,
	STU_COC	NUMBER		NULL,
	STU_PRO	NUMBER		NULL
);

DROP TABLE RECORD;

CREATE TABLE RECORD (
	REC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	REC_CATE	VARCHAR2(10)		NULL,
	REC_YR	NUMBER		NULL,
	REC_SEM	NUMBER		NULL,
	REC_PER	NUMBER		NULL,
	REC_RSN	VARCHAR2(500)		NULL,
	REC_DT	DATE		NULL,
	REC_YN	NUMBER		NULL
);

DROP TABLE TEST_DETAIL;

CREATE TABLE TEST_DETAIL (
	TD_CD	NUMBER		NOT NULL,
	TEQ_CD	NUMBER		NOT NULL,
	ST_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	TD_ANSWER	NUMBER		NULL
);

DROP TABLE LEC_APPLY;

CREATE TABLE LEC_APPLY (
	LECA_CD	NUMBER		NOT NULL,
	SUB_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	PRO_CD	NUMBER		NOT NULL,
	LECA_CATE	VARCHAR2(10)		NULL,
	LECA_YR	NUMBER		NULL,
	LECA_SEM	NUMBER		NULL,
	LECA_NM	VARCHAR2(50)		NULL,
	LECA_CON	VARCHAR2(500)		NULL,
	LECA_TRG	NUMBER		NULL,
	LECA_CRD	NUMBER		NULL,
	LECA_PER	NUMBER		NULL,
	LECA_MAX	NUMBER		NULL,
	LECA_TM1	DATE		NULL,
	LECA_TM2	DATE		NULL,
	LECA_ROOM	VARCHAR2(50)		NULL,
	LECA_UNIT	NUMBER		NULL,
	LECA_BOOK	VARCHAR2(300)		NULL,
	LECA_NOTE	VARCHAR2(500)		NULL,
	LECA_DT	DATE		NULL,
	LECA_GRADE	NUMBER		NULL,
	LECA_IMSI	NUMBER		NULL,
	LECA_YN	NUMBER		NULL
);

DROP TABLE COLLEGE;

CREATE TABLE COLLEGE (
	COL_CD	NUMBER		NOT NULL,
	COL_NM	VARCHAR2(50)		NULL,
	COL_CRD	NUMBER		NULL,
	COL_FEE	NUMBER		NULL
);

DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT (
	DEP_CD	NUMBER		NOT NULL,
	COL_CD	NUMBER		NOT NULL,
	DEP_NM	VARCHAR2(50)		NULL,
	DEP_MRC	NUMBER		NULL,
	DEP_MOC	NUMBER		NULL,
	DEP_CRC	NUMBER		NULL,
	DEP_COC	NUMBER		NULL,
	DEP_MAX	NUMBER		NULL,
	Field7	VARCHAR2(15)		NULL
);

DROP TABLE LEC_NOTICE;

CREATE TABLE LEC_NOTICE (
	LNTC_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	LNTC_TTL	VARCHAR2(200)		NULL,
	LNTC_CON	VARCHAR2(1000)		NULL,
	LNTC_REG	DATE		NULL,
	LNTC_UPD	DATE		NULL
);

DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MEM_CD	NUMBER		NOT NULL,
	MEM_NM	VARCHAR2(30)		NULL,
	MEM_NME	VARCHAR2(30)		NULL,
	MEM_TEL	VARCHAR2(15)		NULL,
	MEM_ZIP	NUMBER		NULL,
	MEM_ADDR1	VARCHAR2(100)		NULL,
	MEM_ADDR2	VARCHAR2(300)		NULL,
	MEM_REG1	VARCHAR2(6)		NULL,
	MEM_REG2	VARCHAR2(7)		NULL,
	MEM_ML	VARCHAR2(30)		NULL,
	MEM_PASS	VARCHAR2(15)		NULL,
	MEM_BANK	VARCHAR2(20)		NULL,
	MEM_DEPO	VARCHAR2(30)		NULL,
	MEM_ACT	VARCHAR2(20)		NULL,
	MEM_FNM	NUMBER		NULL,
	MEM_FPT	VARCHAR2(260)		NULL
);

DROP TABLE SCHEDULE;

CREATE TABLE SCHEDULE (
	SCH_CD	NUMBER		NOT NULL,
	MEM_CD	NUMBER		NOT NULL,
	SCH_TTL	VARCHAR2(50)		NULL,
	SCH_ST	DATE		NULL,
	SCH_EN	DATE		NULL
);

DROP TABLE PROFESSOR;

CREATE TABLE PROFESSOR (
	PRO_CD	NUMBER		NOT NULL,
	DEP_CD	NUMBER		NOT NULL,
	PRO_JOIN	DATE		NULL,
	PRO_RET	DATE		NULL,
	PRO_POS	NUMBER		NULL
);

DROP TABLE MANAGER;

CREATE TABLE MANAGER (
	MGR_CD	NUMBER		NOT NULL,
	MGR_DIV	VARCHAR2(10)		NULL,
	MGR_POS	VARCHAR2(10)		NULL,
	MGR_JOIN	DATE		NULL,
	MGR_RET	DATE		NULL
);

DROP TABLE LECTURE;

CREATE TABLE LECTURE (
	LEC_CD	NUMBER		NOT NULL,
	LEC_YN	NUMBER		NULL,
	LEC_HCNT	NUMBER		NULL
);

DROP TABLE STU_LEC;

CREATE TABLE STU_LEC (
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	SL_SCORE	NUMBER		NULL
);

DROP TABLE WISH;

CREATE TABLE WISH (
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL
);

DROP TABLE NOTICE_FILE;

CREATE TABLE NOTICE_FILE (
	NTCF_CD	NUMBER		NOT NULL,
	NTC_CD	NUMBER		NOT NULL,
	NTCF_NM	VARCHAR2(100)		NULL,
	NTCF_PT	VARCHAR2(260)		NULL
);

DROP TABLE PORTLET;

CREATE TABLE PORTLET (
	PO_CD	NUMBER		NOT NULL,
	MEM_CD	NUMBER		NOT NULL,
	PO_CATE	VARCHAR2(10)		NULL,
	PO_GB	VARCHAR2(10)		NULL,
	PO_SEQ	NUMBER		NULL,
	PO_YN	NUMBER		NULL
);

DROP TABLE FACILITY;

CREATE TABLE FACILITY (
	FAC_CD	NUMBER		NOT NULL,
	FAC_NM	VARCHAR2(40)		NULL
);

DROP TABLE QNA;

CREATE TABLE QNA (
	QNA_CD	NUMBER		NOT NULL,
	MEM_CD	NUMBER		NOT NULL,
	QNA_TTL	VARCHAR2(100)		NULL,
	QNA_CON	VARCHAR2(1000)		NULL,
	QNA_YN	NUMBER		NULL,
	QNA_DT	DATE		NULL,
	QNA_HIT	NUMBER		NULL
);

DROP TABLE QNA_REPLY;

CREATE TABLE QNA_REPLY (
	QNA_CD	NUMBER		NOT NULL,
	QNAR_CON	VARCHAR2(1000)		NULL,
	QNAR_DT	DATE		NULL
);

DROP TABLE TASK_SUBMIT;

CREATE TABLE TASK_SUBMIT (
	TSUB_CD	NUMBER		NOT NULL,
	TASK_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	TSUB_DT	DATE		NULL,
	TSUB_CON	VARCHAR2(500)		NULL,
	TSUB_FNM	VARCHAR2(100)		NULL,
	TSUB_SCORE	NUMBER		NULL
);

DROP TABLE WEEKPLAN;

CREATE TABLE WEEKPLAN (
	WP_NO	NUMBER		NOT NULL,
	LECA_CD	NUMBER		NOT NULL,
	WP_CON	VARCHAR2(500)		NULL
);

DROP TABLE LEC_QNA;

CREATE TABLE LEC_QNA (
	LQNA_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	LQNA_TTL	VARCHAR2(150)		NULL,
	LQNA_CON	VARCHAR2(1000)		NULL,
	LQNA_DT	DATE		NULL,
	LQNA_HIT	NUMBER		NULL
);

DROP TABLE LEC_QNAR;

CREATE TABLE LEC_QNAR (
	LQNA_CD	NUMBER		NOT NULL,
	LQNAR_CON	VARCHAR2(500)		NULL,
	LQNAR_DT	DATE		NULL
);

DROP TABLE LEC_DATA;

CREATE TABLE LEC_DATA (
	LDT_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	LDT_FNM	VARCHAR2(100)		NULL,
	LDT_DT	DATE		NULL
);

DROP TABLE ALLOCATION;

CREATE TABLE ALLOCATION (
	ROOM_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	ALT_DAY	VARCHAR2(3)		NULL,
	ALT_ST	DATE		NULL,
	ALT_EN	DATE		NULL
);

DROP TABLE SUBJECT;

CREATE TABLE SUBJECT (
	SUB_CD	NUMBER		NOT NULL,
	SUB_NM	VARCHAR(50)		NULL
);

DROP TABLE TEST;

CREATE TABLE TEST (
	TEST_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	TEST_NM	VARCHAR2(100)		NULL,
	TEST_CON	VARCHAR2(500)		NULL,
	TEST_REG	DATE		NULL,
	TEST_DT	DATE		NULL
);

DROP TABLE TEST_Q;

CREATE TABLE TEST_Q (
	TEQ_CD	NUMBER		NOT NULL,
	TEST_CD	NUMBER		NOT NULL,
	TEQ_NO	VARCHAR2(300)		NULL,
	TEQ_OP1	VARCHAR2(300)		NULL,
	TEQ_OP2	VARCHAR2(300)		NULL,
	TEQ_OP3	VARCHAR2(300)		NULL,
	TEQ_OP4	VARCHAR2(300)		NULL,
	TEQ_ANSWER	NUMBER		NULL
);

DROP TABLE APPROVAL;

CREATE TABLE APPROVAL (
	APPR_CD	NUMBER		NOT NULL,
	APPR_MEM	VARCHAR2(10)		NULL,
	APPR_DT	DATE		NULL,
	APPR_YN	NUMBER		NULL,
	APPR_RSN	VARCHAR2(300)		NULL,
	APPR_CATE	NUMBER		NULL
);

DROP TABLE POPUP;

CREATE TABLE POPUP (
	POP_CD	NUMBER		NOT NULL,
	POP_TTL	VARCHAR2(100)		NULL,
	POP_FNM	VARCHAR2(100)		NULL,
	POP_FPT	VARCHAR2(260)		NULL
);

DROP TABLE MAIL;

CREATE TABLE MAIL (
	ML_CD	NUMBER		NOT NULL,
	ML_RCP	NUMBER		NOT NULL,
	ML_SEN	NUMBER		NOT NULL,
	ML_TTL	VARCHAR2(100)		NULL,
	ML_CON	VARCHAR2(1000)		NULL,
	ML_IMSI	NUMBER		NULL,
	ML_TM	DATE		NULL,
	ML_YN	DATE		NULL
);

DROP TABLE MAIL_FILE;

CREATE TABLE MAIL_FILE (
	MLF_CD	NUMBER		NOT NULL,
	ML_CD	NUMBER		NOT NULL,
	MLF_NM	VARCHAR2(100)		NULL,
	MLF_PT	VARCHAR2(260)		NULL
);

DROP TABLE NOTIFICATION;

CREATE TABLE NOTIFICATION (
	NTF_CD	NUMBER		NOT NULL,
	MEM_CD	NUMBER		NOT NULL,
	NTF_CON	VARCHAR2(200)		NULL,
	NTF_TM	DATE		NULL,
	NTF_YN	NUMBER		NULL
);

DROP TABLE COMMON_DETAIL;

CREATE TABLE COMMON_DETAIL (
	COMD_CD	VARCHAR2(10)		NOT NULL,
	COM_CD	VARCHAR2(5)		NOT NULL,
	COMD_NM	VARCHAR2(50)		NULL,
	COMD_CON	VARCHAR2(300)		NULL
);

DROP TABLE COMMON;

CREATE TABLE COMMON (
	COM_CD	VARCHAR2(5)		NOT NULL,
	COM_NM	VARCHAR2(50)		NULL,
	COM_DETAIL	VARCHAR2(300)		NULL,
	COM_REG	DATE		NULL,
	COM_MEM	NUMBER		NULL,
	COM_UPD	DATE		NULL,
	COM_UPCD	NUMBER		NULL
);

DROP TABLE EVALUATION;

CREATE TABLE EVALUATION (
	EVLQ_CD	NUMBER		NOT NULL,
	LEC_CD	NUMBER		NOT NULL,
	STU_CD	NUMBER		NOT NULL,
	EVL_SCORE	NUMBER		NULL,
	EVL_ETC	VARCHAR2(300)		NULL
);

DROP TABLE BUILDING;

CREATE TABLE BUILDING (
	BLD_CD	NUMBER		NOT NULL,
	COL_CD	NUMBER		NOT NULL,
	BLD_NM	VARCHAR2(50)		NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT PK_RESERVATION PRIMARY KEY (
	RSV_CD
);

ALTER TABLE NOTICE ADD CONSTRAINT PK_NOTICE PRIMARY KEY (
	NTC_CD
);

ALTER TABLE A_SCHEDULE ADD CONSTRAINT PK_A_SCHEDULE PRIMARY KEY (
	ASCH_CD
);

ALTER TABLE PAYMENT ADD CONSTRAINT PK_PAYMENT PRIMARY KEY (
	PAY_CD
);

ALTER TABLE P_SCHOLARSHIP ADD CONSTRAINT PK_P_SCHOLARSHIP PRIMARY KEY (
	PSCL_CD
);

ALTER TABLE SCHOLARSHIP ADD CONSTRAINT PK_SCHOLARSHIP PRIMARY KEY (
	SCL_CD
);

ALTER TABLE ROOM ADD CONSTRAINT PK_ROOM PRIMARY KEY (
	ROOM_CD
);

ALTER TABLE CRITERIA ADD CONSTRAINT PK_CRITERIA PRIMARY KEY (
	CRTR_CD
);

ALTER TABLE OBJECTION ADD CONSTRAINT PK_OBJECTION PRIMARY KEY (
	OBJ_CD
);

ALTER TABLE TASK ADD CONSTRAINT PK_TASK PRIMARY KEY (
	TASK_CD
);

ALTER TABLE STU_TEST ADD CONSTRAINT PK_STU_TEST PRIMARY KEY (
	ST_CD
);

ALTER TABLE ATTENADENCE ADD CONSTRAINT PK_ATTENADENCE PRIMARY KEY (
	ATEN_CD
);

ALTER TABLE COUNSEL ADD CONSTRAINT PK_COUNSEL PRIMARY KEY (
	CNSL_CD
);

ALTER TABLE EVALUATION_Q ADD CONSTRAINT PK_EVALUATION_Q PRIMARY KEY (
	EVLQ_CD
);

ALTER TABLE STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY (
	STU_CD
);

ALTER TABLE RECORD ADD CONSTRAINT PK_RECORD PRIMARY KEY (
	REC_CD
);

ALTER TABLE TEST_DETAIL ADD CONSTRAINT PK_TEST_DETAIL PRIMARY KEY (
	TD_CD
);

ALTER TABLE LEC_APPLY ADD CONSTRAINT PK_LEC_APPLY PRIMARY KEY (
	LECA_CD
);

ALTER TABLE COLLEGE ADD CONSTRAINT PK_COLLEGE PRIMARY KEY (
	COL_CD
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT PK_DEPARTMENT PRIMARY KEY (
	DEP_CD
);

ALTER TABLE LEC_NOTICE ADD CONSTRAINT PK_LEC_NOTICE PRIMARY KEY (
	LNTC_CD
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	MEM_CD
);

ALTER TABLE SCHEDULE ADD CONSTRAINT PK_SCHEDULE PRIMARY KEY (
	SCH_CD
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (
	PRO_CD
);

ALTER TABLE MANAGER ADD CONSTRAINT PK_MANAGER PRIMARY KEY (
	MGR_CD
);

ALTER TABLE LECTURE ADD CONSTRAINT PK_LECTURE PRIMARY KEY (
	LEC_CD
);

ALTER TABLE STU_LEC ADD CONSTRAINT PK_STU_LEC PRIMARY KEY (
	LEC_CD,
	STU_CD
);

ALTER TABLE WISH ADD CONSTRAINT PK_WISH PRIMARY KEY (
	LEC_CD,
	STU_CD
);

ALTER TABLE NOTICE_FILE ADD CONSTRAINT PK_NOTICE_FILE PRIMARY KEY (
	NTCF_CD
);

ALTER TABLE PORTLET ADD CONSTRAINT PK_PORTLET PRIMARY KEY (
	PO_CD
);

ALTER TABLE FACILITY ADD CONSTRAINT PK_FACILITY PRIMARY KEY (
	FAC_CD
);

ALTER TABLE QNA ADD CONSTRAINT PK_QNA PRIMARY KEY (
	QNA_CD
);

ALTER TABLE QNA_REPLY ADD CONSTRAINT PK_QNA_REPLY PRIMARY KEY (
	QNA_CD
);

ALTER TABLE TASK_SUBMIT ADD CONSTRAINT PK_TASK_SUBMIT PRIMARY KEY (
	TSUB_CD
);

ALTER TABLE WEEKPLAN ADD CONSTRAINT PK_WEEKPLAN PRIMARY KEY (
	WP_NO,
	LECA_CD
);

ALTER TABLE LEC_QNA ADD CONSTRAINT PK_LEC_QNA PRIMARY KEY (
	LQNA_CD
);

ALTER TABLE LEC_QNAR ADD CONSTRAINT PK_LEC_QNAR PRIMARY KEY (
	LQNA_CD
);

ALTER TABLE LEC_DATA ADD CONSTRAINT PK_LEC_DATA PRIMARY KEY (
	LDT_CD
);

ALTER TABLE ALLOCATION ADD CONSTRAINT PK_ALLOCATION PRIMARY KEY (
	ROOM_CD
);

ALTER TABLE SUBJECT ADD CONSTRAINT PK_SUBJECT PRIMARY KEY (
	SUB_CD
);

ALTER TABLE TEST ADD CONSTRAINT PK_TEST PRIMARY KEY (
	TEST_CD
);

ALTER TABLE TEST_Q ADD CONSTRAINT PK_TEST_Q PRIMARY KEY (
	TEQ_CD
);

ALTER TABLE APPROVAL ADD CONSTRAINT PK_APPROVAL PRIMARY KEY (
	APPR_CD
);

ALTER TABLE POPUP ADD CONSTRAINT PK_POPUP PRIMARY KEY (
	POP_CD
);

ALTER TABLE MAIL ADD CONSTRAINT PK_MAIL PRIMARY KEY (
	ML_CD
);

ALTER TABLE MAIL_FILE ADD CONSTRAINT PK_MAIL_FILE PRIMARY KEY (
	MLF_CD
);

ALTER TABLE NOTIFICATION ADD CONSTRAINT PK_NOTIFICATION PRIMARY KEY (
	NTF_CD
);

ALTER TABLE COMMON_DETAIL ADD CONSTRAINT PK_COMMON_DETAIL PRIMARY KEY (
	COMD_CD
);

ALTER TABLE COMMON ADD CONSTRAINT PK_COMMON PRIMARY KEY (
	COM_CD
);

ALTER TABLE EVALUATION ADD CONSTRAINT PK_EVALUATION PRIMARY KEY (
	EVLQ_CD
);

ALTER TABLE BUILDING ADD CONSTRAINT PK_BUILDING PRIMARY KEY (
	BLD_CD
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_FACILITY_TO_RESERVATION_1 FOREIGN KEY (
	FAC_CD
)
REFERENCES FACILITY (
	FAC_CD
);

ALTER TABLE RESERVATION ADD CONSTRAINT FK_MEMBER_TO_RESERVATION_1 FOREIGN KEY (
	MEM_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE NOTICE ADD CONSTRAINT FK_MANAGER_TO_NOTICE_1 FOREIGN KEY (
	MGR_CD
)
REFERENCES MANAGER (
	MGR_CD
);

ALTER TABLE PAYMENT ADD CONSTRAINT FK_STUDENT_TO_PAYMENT_1 FOREIGN KEY (
	STU_ID
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE P_SCHOLARSHIP ADD CONSTRAINT FK_STUDENT_TO_P_SCHOLARSHIP_1 FOREIGN KEY (
	STU_CD
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE P_SCHOLARSHIP ADD CONSTRAINT FK_SCHOLARSHIP_TO_P_SCHOLARSHIP_1 FOREIGN KEY (
	SCL_CD
)
REFERENCES SCHOLARSHIP (
	SCL_CD
);

ALTER TABLE ROOM ADD CONSTRAINT FK_BUILDING_TO_ROOM_1 FOREIGN KEY (
	BLD_CD
)
REFERENCES BUILDING (
	BLD_CD
);

ALTER TABLE CRITERIA ADD CONSTRAINT FK_LEC_APPLY_TO_CRITERIA_1 FOREIGN KEY (
	LECA_CD
)
REFERENCES LEC_APPLY (
	LECA_CD
);

ALTER TABLE OBJECTION ADD CONSTRAINT FK_STU_LEC_TO_OBJECTION_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE OBJECTION ADD CONSTRAINT FK_STU_LEC_TO_OBJECTION_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE TASK ADD CONSTRAINT FK_LECTURE_TO_TASK_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE STU_TEST ADD CONSTRAINT FK_TEST_TO_STU_TEST_1 FOREIGN KEY (
	TEST_CD
)
REFERENCES TEST (
	TEST_CD
);

ALTER TABLE STU_TEST ADD CONSTRAINT FK_STU_LEC_TO_STU_TEST_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE STU_TEST ADD CONSTRAINT FK_STU_LEC_TO_STU_TEST_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE ATTENADENCE ADD CONSTRAINT FK_STU_LEC_TO_ATTENADENCE_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE ATTENADENCE ADD CONSTRAINT FK_STU_LEC_TO_ATTENADENCE_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE COUNSEL ADD CONSTRAINT FK_STUDENT_TO_COUNSEL_1 FOREIGN KEY (
	STU_CD
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE STUDENT ADD CONSTRAINT FK_MEMBER_TO_STUDENT_1 FOREIGN KEY (
	STU_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE STUDENT ADD CONSTRAINT FK_DEPARTMENT_TO_STUDENT_1 FOREIGN KEY (
	DEP_CD
)
REFERENCES DEPARTMENT (
	DEP_CD
);

ALTER TABLE RECORD ADD CONSTRAINT FK_STUDENT_TO_RECORD_1 FOREIGN KEY (
	STU_CD
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE TEST_DETAIL ADD CONSTRAINT FK_TEST_Q_TO_TEST_DETAIL_1 FOREIGN KEY (
	TEQ_CD
)
REFERENCES TEST_Q (
	TEQ_CD
);

ALTER TABLE TEST_DETAIL ADD CONSTRAINT FK_STU_TEST_TO_TEST_DETAIL_1 FOREIGN KEY (
	ST_CD
)
REFERENCES STU_TEST (
	ST_CD
);

ALTER TABLE TEST_DETAIL ADD CONSTRAINT FK_STU_TEST_TO_TEST_DETAIL_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_TEST (
	STU_CD
);

ALTER TABLE LEC_APPLY ADD CONSTRAINT FK_SUBJECT_TO_LEC_APPLY_1 FOREIGN KEY (
	SUB_CD
)
REFERENCES SUBJECT (
	SUB_CD
);

ALTER TABLE LEC_APPLY ADD CONSTRAINT FK_LECTURE_TO_LEC_APPLY_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE LEC_APPLY ADD CONSTRAINT FK_PROFESSOR_TO_LEC_APPLY_1 FOREIGN KEY (
	PRO_CD
)
REFERENCES PROFESSOR (
	PRO_CD
);

ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_COLLEGE_TO_DEPARTMENT_1 FOREIGN KEY (
	COL_CD
)
REFERENCES COLLEGE (
	COL_CD
);

ALTER TABLE LEC_NOTICE ADD CONSTRAINT FK_LECTURE_TO_LEC_NOTICE_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE SCHEDULE ADD CONSTRAINT FK_MEMBER_TO_SCHEDULE_1 FOREIGN KEY (
	MEM_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE PROFESSOR ADD CONSTRAINT FK_MEMBER_TO_PROFESSOR_1 FOREIGN KEY (
	PRO_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE PROFESSOR ADD CONSTRAINT FK_DEPARTMENT_TO_PROFESSOR_1 FOREIGN KEY (
	DEP_CD
)
REFERENCES DEPARTMENT (
	DEP_CD
);

ALTER TABLE MANAGER ADD CONSTRAINT FK_MEMBER_TO_MANAGER_1 FOREIGN KEY (
	MGR_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE STU_LEC ADD CONSTRAINT FK_LECTURE_TO_STU_LEC_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE STU_LEC ADD CONSTRAINT FK_STUDENT_TO_STU_LEC_1 FOREIGN KEY (
	STU_CD
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE WISH ADD CONSTRAINT FK_LECTURE_TO_WISH_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE WISH ADD CONSTRAINT FK_STUDENT_TO_WISH_1 FOREIGN KEY (
	STU_CD
)
REFERENCES STUDENT (
	STU_CD
);

ALTER TABLE NOTICE_FILE ADD CONSTRAINT FK_NOTICE_TO_NOTICE_FILE_1 FOREIGN KEY (
	NTC_CD
)
REFERENCES NOTICE (
	NTC_CD
);

ALTER TABLE PORTLET ADD CONSTRAINT FK_MEMBER_TO_PORTLET_1 FOREIGN KEY (
	MEM_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE QNA ADD CONSTRAINT FK_MEMBER_TO_QNA_1 FOREIGN KEY (
	MEM_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE QNA_REPLY ADD CONSTRAINT FK_QNA_TO_QNA_REPLY_1 FOREIGN KEY (
	QNA_CD
)
REFERENCES QNA (
	QNA_CD
);

ALTER TABLE TASK_SUBMIT ADD CONSTRAINT FK_TASK_TO_TASK_SUBMIT_1 FOREIGN KEY (
	TASK_CD
)
REFERENCES TASK (
	TASK_CD
);

ALTER TABLE TASK_SUBMIT ADD CONSTRAINT FK_STU_LEC_TO_TASK_SUBMIT_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE TASK_SUBMIT ADD CONSTRAINT FK_STU_LEC_TO_TASK_SUBMIT_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE WEEKPLAN ADD CONSTRAINT FK_LEC_APPLY_TO_WEEKPLAN_1 FOREIGN KEY (
	LECA_CD
)
REFERENCES LEC_APPLY (
	LECA_CD
);

ALTER TABLE LEC_QNA ADD CONSTRAINT FK_STU_LEC_TO_LEC_QNA_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE LEC_QNA ADD CONSTRAINT FK_STU_LEC_TO_LEC_QNA_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE LEC_QNAR ADD CONSTRAINT FK_LEC_QNA_TO_LEC_QNAR_1 FOREIGN KEY (
	LQNA_CD
)
REFERENCES LEC_QNA (
	LQNA_CD
);

ALTER TABLE LEC_DATA ADD CONSTRAINT FK_LECTURE_TO_LEC_DATA_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE ALLOCATION ADD CONSTRAINT FK_ROOM_TO_ALLOCATION_1 FOREIGN KEY (
	ROOM_CD
)
REFERENCES ROOM (
	ROOM_CD
);

ALTER TABLE ALLOCATION ADD CONSTRAINT FK_LECTURE_TO_ALLOCATION_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE TEST ADD CONSTRAINT FK_LECTURE_TO_TEST_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES LECTURE (
	LEC_CD
);

ALTER TABLE TEST_Q ADD CONSTRAINT FK_TEST_TO_TEST_Q_1 FOREIGN KEY (
	TEST_CD
)
REFERENCES TEST (
	TEST_CD
);

ALTER TABLE MAIL ADD CONSTRAINT FK_MEMBER_TO_MAIL_1 FOREIGN KEY (
	ML_RCP
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE MAIL_FILE ADD CONSTRAINT FK_MAIL_TO_MAIL_FILE_1 FOREIGN KEY (
	ML_CD
)
REFERENCES MAIL (
	ML_CD
);

ALTER TABLE NOTIFICATION ADD CONSTRAINT FK_MEMBER_TO_NOTIFICATION_1 FOREIGN KEY (
	MEM_CD
)
REFERENCES MEMBER (
	MEM_CD
);

ALTER TABLE COMMON_DETAIL ADD CONSTRAINT FK_COMMON_TO_COMMON_DETAIL_1 FOREIGN KEY (
	COM_CD
)
REFERENCES COMMON (
	COM_CD
);

ALTER TABLE EVALUATION ADD CONSTRAINT FK_EVALUATION_Q_TO_EVALUATION_1 FOREIGN KEY (
	EVLQ_CD
)
REFERENCES EVALUATION_Q (
	EVLQ_CD
);

ALTER TABLE EVALUATION ADD CONSTRAINT FK_STU_LEC_TO_EVALUATION_1 FOREIGN KEY (
	LEC_CD
)
REFERENCES STU_LEC (
	LEC_CD
);

ALTER TABLE EVALUATION ADD CONSTRAINT FK_STU_LEC_TO_EVALUATION_2 FOREIGN KEY (
	STU_CD
)
REFERENCES STU_LEC (
	STU_CD
);

ALTER TABLE BUILDING ADD CONSTRAINT FK_COLLEGE_TO_BUILDING_1 FOREIGN KEY (
	COL_CD
)
REFERENCES COLLEGE (
	COL_CD
);

